ssoconfig.admin_settings_form:
  path: '/admin/config/ssoconfig/adminsettings'
  defaults:
    _form: '\Drupal\ssoconfig\Form\SettingForm'
    _title: 'SSO configuration'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

