maintenance_exempt.settings:
  type: config_object
  label: 'Maintenance Exempt settings'
  mapping:
    query_key:
      type: string
      label: 'Exemption query string'
    exempt_ips:
      type: string
      label: 'Exempt IPs'
