# Schema for the configuration files of the GTM dataLayer Form module.

gtm_datalayer_forms.gtm_datalayer_form.*:
  type: config_entity
  label: 'dataLayer Form settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    form:
      type: string
      label: 'Form ID'
    plugin:
      type: string
      label: 'Plugin'
    weight:
      type: integer
      label: 'Weight'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Access Condition'
